#!/bin/sh

# source config file
. ./config

#verify config file
if [ "$disk" = "" -o "$username" = "" -o "$password" = "" -o "$region" = "" -o "city" = "" -o "$keymap" = "" ]
	then
	echo "incorrect config file"
	exit
fi

# verify uefi
if [ ! -d "/sys/firmware/efi" ]
  then
  echo "this system isn't a uefi system"
  exit
fi

# verify internet connection
wget -q --spider 1.1.1.1
if ! [ $? -eq 0 ]; then
    echo "this system isn't connected to the internet"
    exit
fi

# update system clock
timedatectl set-ntp true

# partition disk
parted $disk -- mklabel gpt
parted $disk -- mkpart primary 550MiB 100%
parted $disk -- mkpart ESP fat32 0% 550MiB
parted $disk -- set 2 esp on

# format partitions
mkfs.xfs "$disk"1
mkfs.fat -F 32 "$disk"2

# mount filesystems 
mkdir /mnt
mount "$disk"1 /mnt
mkdir /mnt/boot
mount "$disk"2 /mnt/boot

# sort mirrors
reflector --sort rate -l 10 --save /etc/pacman.d/mirrorlist

# install arch linux and software
pacstrap /mnt base base-devel linux-zen linux-firmware doas networkmanager vim git

# generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

# post install
arch-chroot /mnt ./post_install
