#!/bin/sh

# sort mirrors
reflector --sort rate -l 10 --save /etc/pacman.d/mirrorlist

# install software
pacman -Sy
pacman -S --noconfirm base-devel
pacman -R --noconfirm sudo
pacman -S --noconfirm doas networkmanager vim git

# source config file
. ./config

# set time zone
ln -sf /usr/share/zoneinfo/"$region"/"$city" /etc/localtime
hwclock --systohc

# generate locale
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen

# set keymap
echo "KEYMAP=$keymap" > /etc/vconsole.conf

# network configuration
echo "$hostname" > /etc/hostname
echo "127.0.0.1        localhost
::1              localhost
127.0.1.1        $hostname" > /etc/hosts

# set root password
echo -e "$password\n$password" | passwd

# create user
useradd -m "$username"
echo -e "$password\n$password" | passwd $username

# add user to doas
echo "permit $username as root" > /etc/doas.conf

# install systemd boot
mkdir /mnt/boot/efi
mount "$disk"2 /mnt/boot/efi
bootctl install
echo "default  arch.conf
timeout  0
console-mode max
editor   no" > /efi/loader/loader.conf

# enable network manager
systemctl enable NetworkManager

# add multilib support
echo -e "\n\n
[multilib]
Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf

# update
pacman -Syyu --noconfirm
