#!/bin/sh

# sort mirrors
reflector --sort rate -l 10 --save /etc/pacman.d/mirrorlist

# install software
pacman -Sy
pacman -S --noconfirm base-devel
pacman -R --noconfirm sudo
pacman -S --noconfirm doas networkmanager vim git grub efibootmgr dosfstools os-prober mtools

# source config file
. ./config

# set time zone
ln -sf /usr/share/zoneinfo/"$region"/"$city" /etc/localtime
hwclock --systohc

# generate locale
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen

# set keymap
echo "KEYMAP=$keymap" > /etc/vconsole.conf

# network configuration
echo "$hostname" > /etc/hostname
echo "127.0.0.1        localhost
::1              localhost
127.0.1.1        $hostname" > /etc/hosts

# lock root password
passwd -l root

# create user
useradd -m "$username"
echo -e "$password\n$password" | passwd $username

# add user to doas
echo "permit $username as root" > /etc/doas.conf

# grub
mkdir /boot/EFI
mount $bootPartition /boot/EFI
grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
cp grub /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

# enable network manager
systemctl enable NetworkManager

# add multilib support
echo -e "\n\n
[multilib]
Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf

# update
pacman -Syyu --noconfirm
