#!/bin/sh

# install paru
pacman -S --noconfirm cargo
su "$username"
cd ~
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si --noconfirm
exit

# install i3 window manager
pacman -S --noconfirm i3-gaps i3lock
